export const GET_CITYWEATHER_REQUESTED = 'GET_CITYWEATHER_REQUESTED';
export const GET_CITYWEATHER_SUCCESS = 'GET_CITYWEATHER_SUCCESS';
export const DELETE_CITYWEATHER_REQUESTED = 'DELETE_CITYWEATHER_REQUESTED';
export const DELETE_CITYWEATHER_SUCCESS = 'DELETE_CITYWEATHER_SUCCESS';
export const UPDATE_CITYWEATHER_REQUESTED = 'UPDATE_CITYWEATHER_REQUESTED';
export const UPDATE_CITYWEATHER_SUCCESS = 'UPDATE_CITYWEATHER_SUCCESS';
export const CITYWEATHER_FAILED = 'CITYWEATHER_FAILED';